<?php

/**
 * Log excecuted information in file
 * @param  array  $error_log [This is an array of infoamtion that user want to check in log file]
 * @return [true]            
 */
function write_logs($error_log = array()) {
  global $user, $base_url, $base_path;  
  $error_log['user_id'] = $user->uid;   
  $border = PHP_EOL . str_repeat("+", 120) . PHP_EOL;
  $error_log = $border . print_r($error_log, true) . $border;    
  //Save string to log in drupal root, use FILE_APPEND to append.
  file_put_contents(DRUPAL_ROOT . '/tmp/site_log_'. date("Y-m-d--h-i") . '.txt', $error_log, FILE_APPEND);  
  return true;
}


/**
 * Use this commented code in file where you want to track code log.
 */
/*
$error_log = array(
  'date' => date('Y-m-d h:m:s') ,
  'file_name' => $_SERVER['SCRIPT_FILENAME'],
  'ip_address' => $_SERVER['REMOTE_ADDR'] . ' - ' . date("F j, Y, g:i:s a") ,
  'Message' => "Calling inside " . FUNCTION,
  'method' => FUNCTION,
  'session' => $_SESSION,
  'url_access' => $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'],
  //'file_access' => FILE, 
  //'line_access' => LINE
);

//data tracking
write_logs($error_log);
*/

